version: "3.8"
 
services:
  frontend:
    build: ./vue-project
    image: azuremicroserviceacr10242140.azurecr.io/frontend
    container_name: azure-microservice_frontend
    ports:
      - 80:80
    restart: always
    depends_on:
      - backend
    # links:
    #   - backend
    environment:
      BASE_URL: http://backend:7012
  backend:
    build: ./backend
    image: azuremicroserviceacr10242140.azurecr.io/backend
    container_name: azure-microservice_backend
    ports:
      - 7012:7012
    restart: always
    # environment: 
    #   DB_URL: mongodb://db/first_volume
  # db:
  #   image: mongo:4.0-xenial
  #   ports:
  #     - 27017:27017
    # volumes:
    #   - first_volume:/data/db 
# volumes:
  # first_volume: